spring.datasource.url=jdbc:postgresql://localhost:5432/burgerdb
spring.datasource.username=postgres
spring.datasource.password=0701
spring.jpa.hibernate.ddl-auto=create
spring.jpa.show-sql=true
server.port=9000
logging.level.org.hibernate.SQL=DEBUG
logging.level.org.hibernate.jdbc.bind=TRACE